### ISSUE TITLE
Can I use this in my project?

### ISSUE THREAD

**Issue by NuclearC** [Matheus28/wsuv#1]
^^

**Comment by Matheus28** [comment]
I would use uWebSockets. This was written when it didn't exist and I'm
currently using it for new things.

**Comment by NuclearC** [comment]
Is there any performance differences? Because Currently I use BSD Sockets for my agar.io server and maybe there is better option?

**Comment by Matheus28** [comment]
Networking is unlikely to be a performance bottleneck for a low number of active connections.

**Comment by NuclearC** [comment]
Oh ok thanks anyway

**Comment by freaky767** [comment]
:O
